### PR TITLE
chore: install pkg-config for PyMySQL compatibility

### PR DESCRIPTION
**Pull request by leangseu-edx**
https://github.com/edx/edx-arch-experiments/issues/349

### CODE REVIEW

**Comment by timmc-edx** [comment]
Same recommendations here about `DEBIAN_FRONTEND=noninteractive` and/or `--no-install-recommends` being needed, and optionally a comment describing which packages are needed for what.

**Comment by leangseu-edx** [comment]
> Same recommendations here about `DEBIAN_FRONTEND=noninteractive` and/or `--no-install-recommends` being needed, and optionally a comment describing which packages are needed for what.

I built this dockerfile. It seems to work without those option.

**Review by timmc-edx — APPROVED** [review]
Hmm, interesting! I'd like to understand why it's a problem for some dockerfiles and not others. But if it works, that's good enough for me. :-)

**Review by mattcarter — APPROVED** [review]
if the container runs correctly w/o the config changes,  LGTM 👍🏻

**Pull request merged**
