### PR TITLE
[BB-6229] chore: cherry-pick requirements upgarde

### PR DESCRIPTION
**Pull request by kaustavb12**
## Description

Cherrypick of #288 

Updating the old version of the some the required packages.

## Supporting information

OpenCraft Internal ticket [BB-6229](https://tasks.opencraft.com/browse/BB-6229)

### CODE REVIEW

**Comment by openedx-webhooks** [comment]
Thanks for the pull request, @kaustavb12!  Please note that it may take us up to several weeks or months to complete a review and merge your PR.

Feel free to add as much of the following information to the ticket as you can:
- supporting documentation
- [Open edX discussion forum threads](https://discuss.openedx.org/)
- timeline information ("this must be merged by XX date", and why that is)
- partner information ("this is a course on edx.org")
- any other information that can help Product understand the context for the PR

All technical communication about the code itself will be done via the GitHub pull request interface. As a reminder, [our process documentation is here](http://edx-developer-guide.readthedocs.org/en/latest/process/overview.html).


Please let us know once your PR is ready for our review and all tests are green.

**Review by 0x29a — APPROVED** [review]
:+1:

- [x] I didn't test this. Instead, I checked that updated packages have the same versions (and updated to the same versions) as they had when PR against `master` has been merged. 
- [x] I read through the changes.

**Comment by natabene** [comment]
@kaustavb12 Thank you for your contribution.

**Review by mattcarter — APPROVED** [review]
approved

**Comment by itsjeyd** [comment]
@mattcarter Looks like this is ready for merge. When you get a minute would you mind hitting the button?

CC @kaustavb12

**Comment by itsjeyd** [comment]
@mattcarter Friendly ping on this. It just needs to be merged :)

**Comment by openedx-webhooks** [comment]
@kaustavb12 🎉 Your pull request was merged!  Please take a moment  to [answer a two question survey](https://docs.google.com/forms/d/e/1FAIpQLSceJOyGJ6JOzfy6lyR3T7EW_71OWUnNQXp68Fymsk3MkNoSDg/viewform?usp=pp_url&entry.1671973413=openedx/edx-notes-api&entry.867055334=https://github.com/openedx/edx-notes-api/pull/298&entry.1484655318=https://github.com/kaustavb12&entry.752974735=2022-07-06+06:46&entry.1917517419=2023-01-24+17:36&entry.2133058324=Yes) so we can improve your experience in the future.

**Pull request merged**
